# Generated by Django 5.2.13 on 2026-09-03 10:29

from django.db import migrations
from django.contrib.auth.models import Group, User
from dotenv import load_dotenv
import os
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission

load_dotenv()

DEFAULT_ACTIONS = ["add", "view", "delete", "change"]

MANAGER_PERMISSIONS = {
    "cms": {
        "certificate": DEFAULT_ACTIONS, 
        "team": DEFAULT_ACTIONS, 
        "teamjoinrequest": DEFAULT_ACTIONS, 
        "userteam": DEFAULT_ACTIONS,
        "event": DEFAULT_ACTIONS,
        "link": DEFAULT_ACTIONS, 
        "internship": DEFAULT_ACTIONS, 
        "document": DEFAULT_ACTIONS, 
        "content": DEFAULT_ACTIONS
    }, 
    "payments": {
        f"paymentclaim": ["view"]
    }
}

def _resolve_permission(app_label, model_name, action):
        content_type = ContentType.objects.get(app_label=app_label, model=model_name)
        codename = f"{action}_{model_name}" if action in DEFAULT_ACTIONS else action
        return Permission.objects.get(codename=codename, content_type=content_type)


def create_manager_group_and_user(apps, schema_editor):
    group, _ = Group.objects.get_or_create(name="Manager")
    
    permissions_to_add = []
    for app_label, models in MANAGER_PERMISSIONS.items():
        for model_name, actions in models.items():
            for action in actions:
                try:
                    permissions_to_add.append(
                        _resolve_permission(app_label, model_name.lower(), action)
                    )
                except (ContentType.DoesNotExist, Permission.DoesNotExist):
                    # Skip silently (or raise) depending on how strict you want
                    # this migration to be about missing permissions.
                    continue
    if permissions_to_add:
        group.permissions.add(*permissions_to_add)

    
    [user, is_created] = User.objects.get_or_create(email=os.environ.get('ADMIN_EMAIL'), username=os.environ.get('ADMIN_USERNAME'), is_staff=True)
    if is_created:
        user.set_password(os.environ.get('ADMIN_PASSWORD'))
    
    user.groups.add(group)
    user.save()

def reverse(apps, schema_editor):
    user = User.objects.get(email=os.environ.get('ADMIN_EMAIL'))
    user.delete()
    
    group = Group.objects.get(name="Manager")
    group.delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'), # But I'm using django's default user model
        ('payments', '0002_alter_adminnotification_reference_code_and_more'),
        ('cms', '0002_event_team_certificate_link_internship_document_and_more'),
        ('contenttypes', '0002_remove_content_type_name')
    ]

    operations = [
        migrations.RunPython(create_manager_group_and_user, reverse)
    ]
